---
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS INSTANCES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


global_config:
  environment_name: cp4waiops
  cloud_platform: existing-ocp
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS Pull Registires
  # --------------------------------------------------------------------------------------------------------------------------------------
  entitled_registry: cp.icr.io
  entitled_registry_user: cp
  catalog_image: icr.io/cpopen/ibm-operator-catalog:latest
  # Create Welcome Cards in CP4WAIOps
  create_cards: true
  # Create App Menu Items in OCP
  create_ocp_items: true
  # Use this Password for all Instances
  global_password: P4ssw0rd!
  # Set this value to True to accept all licenses
  accept_all_licenses: False
  # Create Notifications in OCP
  create_ocp_notifications: true
  position_ocp_notifications: BannerTop
  position_final_ocp_notification: BannerTop
  # Key to decrypt Licenses
  # license_token: NONE


openshift:
- name: "mycluster"
  ocp_version: "4.12"
  cluster_name: "mycluster"
  domain_name: example.com
  openshift_storage:
  - storage_name: auto-storage
    storage_type: auto
    # Alternatively use
    #storage_name: ibm-roks-storage
    #storage_type: custom
    #ocp_storage_class_file: ibmc-file-gold-gid
    #ocp_storage_class_block: ibmc-block-gold


cp4waiops:
- project: cp4waiops-addons
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS INSTANA
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-instana
    kind: Instana
    install: true
    instana_version: 247-0

    # ---------------------------------------------------------------------
    # INSTANA LICENSE
    sales_key: 'NONE'
    agent_key: 'NONE'

    # ---------------------------------------------------------------------
    # INSTANA ADMIN LOGIN
    # Admin User Name
    instana_admin_user: "admin@instana.local"
    # Admin User Password (OVERRIDES GLOBAL PASSWORD)
    #instana_admin_pass: 'P4ssw0rd!'
    
    # ---------------------------------------------------------------------
    # INSTALL INSTANA AGENT
    install_agent: true

    # --------------------------------------------------------------------------------------------------------------------------------------
    # INTEGRATIONS
    integrate_cp4waiops: true
    #integrate_turbonomic: true
    
    # --------------------------------------------------------------------------------------------------------------------------------------
    # Storage Classes Override for this Instance (see comment below)
    # --------------------------------------------------------------------------------------------------------------------------------------
    #storage_class_file: automatic
    #storage_class_block: automatic


# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS USAGE
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS Storage Classes
# --------------------------------------------------------------------------------------------------------------------------------------

# Override the Storage Class auto detection (not_configured, ibmc-file-gold-gid, rook-cephfs, nfs-client, ...)
#storage_class_file: automatic
#storage_class_file: ibmc-file-gold-gid               # ROKS
#storage_class_file: ocs-storagecluster-cephfs        # ODF
#storage_class_file: ibmc-vpc-block-10iops-tier       # IBM VPC
#storage_class_file: rook-cephfs                      # FYRE
#storage_class_file: nfs-client                       # TEC

#storage_class_block: automatic
#storage_class_block: ibmc-block-gold                 # ROKS
#storage_class_block: ocs-storagecluster-ceph-rbd     # ODF
#storage_class_block: ibmc-vpc-block-10iops-tier      # IBM VPC
#storage_class_block: rook-cephfs                     # FYRE
#storage_class_block: nfs-client                      # TEC

