

global_config:
  environment_name: cp4waiops
  cloud_platform: existing-ocp
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS Pull Registires
  # --------------------------------------------------------------------------------------------------------------------------------------
  entitled_registry: cp.icr.io
  entitled_registry_user: cp
  catalog_image: icr.io/cpopen/ibm-operator-catalog:latest
  # Create Welcome Cards in CP4WAIOps
  create_cards: true
  # Create App Menu Items in OCP
  create_ocp_items: true
  # Use this Password for all Instances
  # Deployment will not work if these aren't changed
  global_password: CHANGEME
  # Set this value to True to accept all licenses
  accept_all_licenses: False
  # Create Notifications in OCP
  create_ocp_notifications: true
  position_ocp_notifications: BannerTop
  position_final_ocp_notification: BannerTop
  # Key to decrypt Licenses
  # license_token: NONE


openshift:
- name: "mycluster"
  ocp_version: "4.12"
  cluster_name: "mycluster"
  domain_name: example.com
  openshift_storage:
  - storage_name: auto-storage
    storage_type: auto
    # Alternatively use
    #storage_name: ibm-roks-storage
    #storage_type: custom
    #ocp_storage_class_file: ibmc-file-gold-gid
    #ocp_storage_class_block: ibmc-block-gold


cp4waiops:
- project: cp4waiops
  instances:

    
  # --------------------------------------------------------------------------------------------------------------------------------------
  # INSTALL CP4WAIOPS Demo Content
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-demo-content
    kind: CP4WAIOpsDemoContent
    install: true


    # ---------------------------------------------------------------------
    # TRAINING
    # Train the Models based on pre-canned content

    training_create_training_temporal: false

    training_load_data_logs: false
    training_create_training_logs: false
    training_run_training_logs: false

    training_load_data_snow: false
    training_create_training_snow: false
    training_run_training_snow: false

    training_load_data_metrics: false
    training_create_training_metrics: false
    training_run_training_metrics: false

    training_data_url: https://github.com/niklaushirt/
    training_data_repo: cp4waiops-trainingdata


    # ---------------------------------------------------------------------
    # TOPOLOGY
    # Install DemoApps Application
    install_demoapps: true
    # Install DemoApps K8s Observer
    install_demoapps_observer: false
    # Create Topology
    create_topology_templates: false
    create_topology_apps: false
    # Create Custom overlay topology
    install_custom_topology: false

    # ---------------------------------------------------------------------
    # RUNBOOKS
    # Install AWX and create Runbooks
    install_awx: true
    load_awx_playbooks: true
    integrate_awx: false
    load_runbooks: false
    create_runbook_policy: false


    # ---------------------------------------------------------------------
    # Demo UI
    install_demo_ui: false
    demoui_slack_url: https://aiopsdemohq.slack.com/sign_in_with_password
    # demoui_slack_url: https://aiops-fry2953.slack.com/x-p1624757694871-3716524482480-3705437209041/messages/C01JZLFJFMJ
    demoui_slack_user: ibmaiopsdemo@gmail.com
    demoui_slack_pwd: CHANGEME
    demoui_admin_mode: "true"
    demoui_simulation_mode: "true"

    demoui_user: demo
    # Password for the Demo UI (OVERRIDES GLOBAL PASSWORD)
    #demoui_pwd: CHANGEME


    # ---------------------------------------------------------------------
    # LDAP
    install_ldap: true
    # ldap domain
    ldap_domain: ibm.com
    # ldap base
    ldap_base: dc=ibm,dc=com
    # LDAP Admin Password (OVERRIDES GLOBAL PASSWORD)
    #ldap_admin_password: CHANGEME
    # LDAP Password for all Users (OVERRIDES GLOBAL PASSWORD)
    #ldap_user_password: CHANGEME
    # ldap namespace
    ldap_namespace: openldap
    # ldap namespace
    ldap_register: false

    # ---------------------------------------------------------------------
    # MISC PARAMETERS (you should not modify those)
    # Create external routes (needed to create demo content)
    create_external_routes: false

    # Create a valid ingress certificate (needed for Slack integration)
    create_valid_ingress_certificate: false

    # Create Policy for Incident Creation
    create_incident_policy: false

    # Create Kafka connection for Log inception (needed to create log anomalies in the demo environment)
    create_log_connection: false

    # Create Service Account
    create_account: true



    # ---------------------------------------------------------------------
    # OUTPUT
    # Print all logins
    print_logins: false
    # Open the relevant Web UIs
    open_web_ui: false




- project: cp4waiops-addons
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS ELK
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-elk
    kind: ELK
    install: true




# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS USAGE
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS Storage Classes
# --------------------------------------------------------------------------------------------------------------------------------------

# Override the Storage Class auto detection (not_configured, ibmc-file-gold-gid, rook-cephfs, nfs-client, ...)
#storage_class_file: automatic
#storage_class_file: ibmc-file-gold-gid               # ROKS
#storage_class_file: ocs-storagecluster-cephfs        # ODF
#storage_class_file: ibmc-vpc-block-10iops-tier       # IBM VPC
#storage_class_file: rook-cephfs                      # FYRE
#storage_class_file: nfs-client                       # TEC

#storage_class_block: automatic
#storage_class_block: ibmc-block-gold                 # ROKS
#storage_class_block: ocs-storagecluster-ceph-rbd     # ODF
#storage_class_block: ibmc-vpc-block-10iops-tier      # IBM VPC
#storage_class_block: rook-cephfs                     # FYRE
#storage_class_block: nfs-client                      # TEC

