---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waiops-demo-ui-python
  namespace: cp4waiops
  labels:
      app: waiops-demo-ui-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waiops-demo-ui-python
  template:
    metadata:
      labels:
        app: waiops-demo-ui-python
    spec:
      containers:
      - image: niklaushirt/cp4waiops-demo-ui-python:0.57
        imagePullPolicy: Always
        name: waiops-demo-ui-python
        command:
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "550m"
            memory: "550Mi"
          readinessProbe:                 
            failureThreshold: 9           
            httpGet:                      
              path: /health          
              port: 8000                  
              scheme: HTTP           
            initialDelaySeconds: 60       
            periodSeconds: 10             
            successThreshold: 1           
            timeoutSeconds: 3
        envFrom:
        - configMapRef:
            name:  demo-ui-python-config
        - configMapRef:
            name:  demo-ui-python-config-events
        - configMapRef:
            name:  demo-ui-python-config-logs
        - configMapRef:
            name:  demo-ui-python-config-metrics
      serviceAccountName: demo-ui-python-admin
---
apiVersion: v1
kind: Service
metadata:
  name: waiops-demo-ui-python-service
  namespace: cp4waiops
spec:
  selector:
    app: waiops-demo-ui-python
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name:  waiops-demo-ui-python
  namespace: cp4waiops
spec:
  to:
    kind: Service
    name: waiops-demo-ui-python-service
    weight: 100
  port:
    targetPort: 8000
  wildcardPolicy: None

