
apiVersion: batch/v1
kind: Job
metadata:
  name: demo-inception-job
  namespace: cp4waiops-installer
spec:
  serviceAccountName: demo-admin
  template:
    spec:
      containers:
        - name: load
          image: quay.io/niklaushirt/cp4waiops-tools:2.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "2024Mi"
              cpu: "1200m"
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/bash
              set -x

              export GIT_REPO=https://github.com/niklaushirt/cp4waiops-trainingdata.git
              git clone $GIT_REPO
              cd cp4waiops-trainingdata
              ./tools/01_demo/robotshop_incident_memory.sh
              sleep 6000000
      restartPolicy: Never

  backoffLimit: 4
