#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS v3.5.0
#
#  CloudPak for Watson AIOps
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - IBM Operator
#  - AI Manager
#  - Demo Content
#     - OpenLDAP & Register with AI Manager
#     - RobotShop Demo App
#     - Demo Service Account 
#     - AWX (Open Source Ansible Tower) with preloaded Playbooks
#     - Disables ASM Service match rule 
#     - Train Models
#       - Create Training Definitions (TG, LAD, CR, SI. MET, Turn off RSA) 
#       - Create Training Data (LAD, SNOW, MET) 
#       - Train Models (TG, LAD, CR, SI, MET) 
#     - Topology
#       - Create K8s Observer
#       - Create ASM merge rules
#       - Load ASM merge Topology
#       - Create AI Manager Application
#     - Creates valid certificate for Ingress (Slack) 
#     - External Routes (Flink, Topology, ...)
#     - Disables ASM Service match rule 
#     - Create Policy Creation for Stories and Runbooks 
#  - Event Manager
#  - Demo Content
#    - Topology
#      - Create ASM merge rules
#      - Load ASM merge Topology
#      - Create AI Manager Application
#  - Turbonomic

# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: installer-default-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cp4waiops-install-custom
  namespace: default
spec:
  serviceAccountName: installer-default-default
  template:
    spec:
      containers:
        - name: install
          image: niklaushirt/cp4waiops-tools:1.3
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "1256Mi"
              cpu: "1200m"
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/bash
              #set -x

              echo "*****************************************************************************************************************************"
              echo " ✅ STARTING: INSTALL AI Manager with Demo Content"
              echo "*****************************************************************************************************************************"
              echo ""
              echo ""
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 📥 Clone Repo $INSTALL_REPO"
              git clone $INSTALL_REPO
              cd cp4waiops-deployer
              echo ""
              echo ""



              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 📝 Create Config File"
              
              cat <<EOF > ./ansible/configs/cp4waiops-roks-custom.yaml
              cp4waiops:



              - project: cp4waiops
                instances:
                # --------------------------------------------------------------------------------------------------------------------------------------
                # CP4WAIOPS AI Manager
                # --------------------------------------------------------------------------------------------------------------------------------------
                - name: cp4waiops-aimanager
                  kind: AIManager
                  install: true

                  # ---------------------------------------------------------------------
                  # CP4WAIOPS Size of the install (small: PoC/Demo, tall: Production)
                  waiops_size: small
                  # Name of the CP4WAIOPS instance
                  waiops_name: ibm-cp-watson-aiops
                  # Version of the catalog subscription
                  subscription_channel: v3.5


                  



                # --------------------------------------------------------------------------------------------------------------------------------------
                # CP4WAIOPS AI Manager Demo Content
                # --------------------------------------------------------------------------------------------------------------------------------------
                - name: cp4waiops-aimanager-demo-content
                  kind: AIManagerDemoContent
                  install: true


                  # ---------------------------------------------------------------------
                  # TRAINING
                  # Train the Models based on pre-canned content
                  train_models_logs: true
                  train_models_snow: true
                  train_models_metrics: true

                  training_data_url: https://github.com/niklaushirt/
                  training_data_repo: cp4waiops-trainingdata


                  # ---------------------------------------------------------------------
                  # TOPOLOGY
                  # Install RobotShop Application
                  install_robotshop: true
                  # Create Topology
                  create_topology: true
                  # Create RobotShop overlay topology
                  install_robotshop_topology: true


                  # ---------------------------------------------------------------------
                  # RUNBOOKS
                  # Install AWX and create Runbooks
                  install_awx: true
                  load_awx_playbooks: true
                  integrate_awx_aimanager: true
                  load_aimanager_runbooks: true


                  # ---------------------------------------------------------------------
                  # Demo UI
                  install_demo_ui: true
                  demoui_slack_url: https://app.slack.com/client/T0DBLALE5/C03MYASSZ2Q
                  # demoui_slack_url: https://aiops-fry2953.slack.com/x-p1624757694871-3716524482480-3705437209041/messages/C01JZLFJFMJ
                  demoui_slack_user: ibmaiopsdemo@gmail.com
                  demoui_slack_pwd: P4ssw0rd!
                  demoui_admin_mode: "true"
                  demoui_simulation_mode: "true"

                  demoui_aimanager_demo_user: demo
                  demoui_aimanager_demo_pwd: P4ssw0rd!


                  # ---------------------------------------------------------------------
                  # LDAP
                  install_ldap: true
                  # ldap domain
                  ldap_domain: ibm.com
                  # ldap base
                  ldap_base: dc=ibm,dc=com
                  # ldap admin password
                  ldap_admin_password: P4ssw0rd!
                  # ldap namespace
                  ldap_namespace: openldap


                  # ---------------------------------------------------------------------
                  # MISC PARAMETERS (you should not modify those)
                  # Create external routes (needed to create demo content)
                  create_external_routes: true

                  # Create a valid ingress certificate (needed for Slack integration)
                  create_valid_ingress_certificate: true

                  # Create Policy for Story Creation
                  create_story_policy: true

                  # Create Kafka connection for Log inception (needed to create log anomalies in the demo environment)
                  create_log_connection: true

                  # Create Service Account
                  create_account: true



                  # ---------------------------------------------------------------------
                  # OUTPUT
                  # Print all logins
                  print_logins: true
                  # Open the relevant Web UIs
                  open_web_ui: true




              - project: cp4waiops-evtmgr
                instances:
                # --------------------------------------------------------------------------------------------------------------------------------------
                # CP4WAIOPS Event Manager
                # --------------------------------------------------------------------------------------------------------------------------------------
                - name: cp4waiops-eventmanager
                  kind: EventManager
                  install: true
                  # Version of the catalog subscription
                  subscription_channel: v1.10
                  starting_csv: noi.v1.6.0
                  noi_version: 1.6.6

                # --------------------------------------------------------------------------------------------------------------------------------------
                # CP4WAIOPS Event Manager Demo Content
                # --------------------------------------------------------------------------------------------------------------------------------------
                - name: cp4waiops-eventmanager
                  kind: EventManagerDemoContent
                  install: true




              - project: cp4waiops-infra
                instances:
                # --------------------------------------------------------------------------------------------------------------------------------------
                # CP4WAIOPS Infrastructure Management
                # --------------------------------------------------------------------------------------------------------------------------------------
                - name: cp4waiops-infrastructure-management
                  kind: InfrastructureManagement
                  install: false
                  # Version of the catalog subscription
                  subscription_channel: v3.5







              - project: cp4waiops-addons
                instances:
                # --------------------------------------------------------------------------------------------------------------------------------------
                # CP4WAIOPS ELK
                # --------------------------------------------------------------------------------------------------------------------------------------
                - name: cp4waiops-elk
                  kind: ELK
                  install: false


                # --------------------------------------------------------------------------------------------------------------------------------------
                # CP4WAIOPS TURBONOMIC
                # --------------------------------------------------------------------------------------------------------------------------------------
                - name: cp4waiops-turbonomic
                  kind: Turbonomic
                  install: true










              # *************************************************************************************************************************************************
              # --------------------------------------------------------------------------------------------------------------------------------------
              # CP4WAIOPS GLOBAL CONFIGURATION
              # --------------------------------------------------------------------------------------------------------------------------------------
              # *************************************************************************************************************************************************


              # --------------------------------------------------------------------------------------------------------------------------------------
              # CP4WAIOPS Storage Classes
              # --------------------------------------------------------------------------------------------------------------------------------------

              # Override the Storage Class auto detection (not_configured, ibmc-file-gold-gid, rook-cephfs, nfs-client, ...)
              storage_class_file: automatic
              #storage_class_file: ibmc-file-gold-gid               # ROKS
              #storage_class_file: ocs-storagecluster-cephfs        # ODF
              #storage_class_file: ibmc-vpc-block-10iops-tier       # IBM VPC
              #storage_class_file: rook-cephfs                      # FYRE
              #storage_class_file: nfs-client                       # TEC
              storage_class_block: automatic
              #storage_class_block: ibmc-block-gold                 # ROKS
              #storage_class_block: ocs-storagecluster-ceph-rbd     # ODF
              #storage_class_block: ibmc-vpc-block-10iops-tier      # IBM VPC
              #storage_class_block: rook-cephfs                     # FYRE
              #storage_class_block: nfs-client                      # TEC



              # --------------------------------------------------------------------------------------------------------------------------------------
              # CP4WAIOPS Pull Registires
              # --------------------------------------------------------------------------------------------------------------------------------------
              entitled_registry: cp.icr.io
              entitled_registry_user: cp
              catalog_image: icr.io/cpopen/ibm-operator-catalog:latest


              #Version of your OCP Cluster (override by setting manually - 4.6, 4.7,...)
              ocp_major_version: automatic
              EOF





              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 🚀 Prepare Ansible"
              ansible-galaxy collection install community.kubernetes:1.2.1
              ansible-galaxy collection install kubernetes.core:2.2.3
              ansible-galaxy collection install cloud.common
              pip install openshift pyyaml kubernetes 
              echo ""
              echo ""



              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 🚀 Starting Installation"
              ansible-playbook ./ansible/00_cp4waiops-install.yaml -e "config_file_path=$CONFIG" -e CP_ENTITLEMENT_KEY=$ENTITLED_REGISTRY_KEY
              echo ""
              echo ""
              echo "*****************************************************************************************************************************"
              echo " ✅ DONE"
              echo "*****************************************************************************************************************************"



              while true
              do
                sleep 1000
              done

          env:
          - name: INSTALL_REPO
            value : "https://github.com/niklaushirt/cp4waiops-deployer.git"
          - name: CONFIG
            #value : "./configs/cp4waiops-roks-aimanager-all-34.yaml"
            value : "./configs/cp4waiops-roks-custom.yaml"
            # The pull token for cp.icr.com from https://myibm.ibm.com/products-services/containerlibrary
          - name: ENTITLED_REGISTRY_KEY
            value : "<REGISTRY_TOKEN>"
      restartPolicy: Never
  backoffLimit: 4