apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cass-operator-community
  namespace: instana-datastores
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cass-operator-community
  source: community-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: instana-datastores
  namespace: instana-datastores
spec:
  targetNamespaces:
    - instana-datastores
  upgradeStrategy: Default