apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: strimzi-kafka-operator
  namespace: instana-datastores
spec:
  channel: stable
  installPlanApproval: Automatic
  name: strimzi-kafka-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: strimzi-cluster-operator.v0.34.0
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: instana-datastores
  namespace: instana-datastores
spec:
  targetNamespaces:
    - instana-datastores
  upgradeStrategy: Default