kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    hdm.ibm.com/lastknownstate: 3518a046ffbfaabe08446c9360535044
  resourceVersion: '4034720'
  name: evtmanager-nciserver-startup-scripts
  uid: 76bfc398-8a51-4626-b459-b2f38b4c8197
  creationTimestamp: '2023-05-10T08:07:47Z'
  managedFields:
    - manager: manager
      operation: Update
      apiVersion: v1
      time: '2023-05-10T08:07:47Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:post-server-start': {}
          'f:pre-server-start': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:hdm.ibm.com/lastknownstate': {}
          'f:labels':
            'f:helm.sh/chart': {}
            'f:hdm.ibm.com/lastreconciled': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:hdm.ibm.com/resourceowner': {}
            'f:managedByUser': {}
            'f:app.kubernetes.io/name': {}
            .: {}
            'f:hdm.ibm.com/chartversion': {}
            'f:release': {}
            'f:app.kubernetes.io/instance': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"c3e19346-f37f-46e6-8b2d-9183d11b2fae"}': {}
  namespace: cp4waiops-evtmgr
  ownerReferences:
    - apiVersion: noi.ibm.com/v1beta1
      kind: NOIFormation
      name: evtmanager
      uid: c3e19346-f37f-46e6-8b2d-9183d11b2fae
      controller: true
      blockOwnerDeletion: true
  labels:
    hdm.ibm.com/resourceowner: evtmanagernoi-ibm-com-v1beta1
    managedByUser: 'false'
    app.kubernetes.io/instance: evtmanager
    release: evtmanager
    hdm.ibm.com/lastreconciled: 2023-05-10-08-19-14-615269171-0000-UTC-m-757-382204293
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: nciserver
    app.kubernetes.io/name: nciserver
    hdm.ibm.com/chartversion: 1.6.6
data:
  post-server-start: |
    #
    # Post server startup script
    #
    echo "Running post-server startup custom scripts"
  pre-server-start: |
    #
    # Pre server startup script
    #
    echo "Running pre-server startup custom scripts"
