#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#         ________  __  ___     ___    ________       
#        /  _/ __ )/  |/  /    /   |  /  _/ __ \____  _____
#        / // __  / /|_/ /    / /| |  / // / / / __ \/ ___/
#      _/ // /_/ / /  / /    / ___ |_/ // /_/ / /_/ (__  ) 
#     /___/_____/_/  /_/    /_/  |_/___/\____/ .___/____/  
#                                           /_/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS
#
#  CloudPak for Watson AIOps
#
#  ©2023 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - ELK
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"

apiVersion: v1                     
kind: Namespace
metadata:
  name: cp4waiops-installer
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cp4waiops-installer-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: cp4waiops-installer
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cp4waiops-install-elk
  namespace: cp4waiops-installer
spec:
  serviceAccountname: cp4waiops-installer-admin
  template:
    metadata:
      labels:
        app: cp4waiops-installer

    spec:
      containers:
        - name: install
          image: quay.io/niklaushirt/cp4waiops-tools:2.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "2024Mi"
              cpu: "1200m"
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/bash
              #set -x

              oc delete ConsoleNotification --all
              oc delete job  -n cp4waiops-installer --ignore-not-found $(oc get job -n cp4waiops-installer|grep load-|awk '{print$1}')
              oc delete pod  -n cp4waiops-installer --ignore-not-found $(oc get po -n cp4waiops-installer|grep load-|awk '{print$1}')

              echo "*****************************************************************************************************************************"
              echo " ✅ STARTING: INSTALL ELK"
              echo "*****************************************************************************************************************************"
              echo ""
              echo ""
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 📥 Clone Repo $INSTALL_REPO"
              git clone $INSTALL_REPO -b cp4waiops_stable
              cd cp4waiops-deployer
              echo ""
              echo ""
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo "This Repo includes those latestet Commits"
              echo "------------------------------------------------------------------------------------------------------------------------------"
              git log|head -n 17
              echo ""
              echo ""


              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 🚀 Prepare Ansible"
              pip install openshift pyyaml kubernetes 
              echo ""
              echo ""



              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 🚀 Starting Installation"
              export ANSIBLE_LOG_PATH=/tmp/ansible.log
              ansible-playbook ./ansible/00_cp4waiops-install.yaml -e "config_file_path=$CONFIG" -e cp_entitlement_key=$ENTITLED_REGISTRY_KEY
              echo ""
              echo ""
              echo "  ⏳ INSTALLATION END TIMESTAMP: $(date)"

              ./tools/98_checkInstallLog.sh

              while true
              do
                sleep 1000
              done



              while true
              do
                sleep 1000
              done

          env:
          - name: INSTALL_REPO
            value : "https://github.com/niklaushirt/cp4waiops-deployer.git"
          - name: CONFIG
            #value : "./configs/cp4waiops-all-34.yaml"
            value : "./configs/cp4waiops-roks-elk.yaml"
          - name: ENTITLED_REGISTRY_KEY
            value : "not_needed"
      restartPolicy: Never
  backoffLimit: 4
