#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#         ________  __  ___     ___    ________       
#        /  _/ __ )/  |/  /    /   |  /  _/ __ \____  _____
#        / // __  / /|_/ /    / /| |  / // / / / __ \/ ___/
#      _/ // /_/ / /  / /    / ___ |_/ // /_/ / /_/ (__  ) 
#     /___/_____/_/  /_/    /_/  |_/___/\____/ .___/____/  
#                                           /_/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS v3.7.1
#
#  CloudPak for Watson AIOps
#
#  ©2023 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Get a Cluster from TechZone: https://techzone.ibm.com/collection/custom-roks-vmware-requests
#   Geograpy: prefer Dallas or London (others might be slower)
#   Worker node count: 5
#   Flavour: b3c.32x128 ❗ 
#   OpenShift Version: 4.12
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - Turbonomic
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"

apiVersion: v1                     
kind: Namespace
metadata:
  name: cp4waiops-installer
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cp4waiops-installer-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: cp4waiops-installer
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cp4waiops-install-turbonomic
  namespace: cp4waiops-installer
spec:
  serviceAccountname: cp4waiops-installer-admin
  template:
    metadata:
      labels:
        app: cp4waiops-installer

    spec:
      containers:
        - name: install
          image: quay.io/niklaushirt/cp4waiops-tools:2.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "2024Mi"
              cpu: "1200m"
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/bash
              #set -x

              oc delete ConsoleNotification --all
              oc delete job  -n cp4waiops-installer --ignore-not-found $(oc get job -n cp4waiops-installer|grep load-|awk '{print$1}')
              oc delete pod  -n cp4waiops-installer --ignore-not-found $(oc get po -n cp4waiops-installer|grep load-|awk '{print$1}')

              echo "*****************************************************************************************************************************"
              echo " ✅ STARTING: INSTALL CP4WAIOps with Demo Content"
              echo "*****************************************************************************************************************************"
              echo ""
              echo "  ⏳ INSTALLATION START TIMESTAMP: $(date)"
              echo ""
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 📥 Clone Repo $INSTALL_REPO"
              git clone $INSTALL_REPO -b cp4waiops_stable
              cd cp4waiops-deployer
              echo ""
              echo ""
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo "This Repo includes those latestet Commits"
              echo "------------------------------------------------------------------------------------------------------------------------------"
              git log|head -n 17
              echo ""
              echo ""


              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 📝 Create Config File"
              
              cat <<EOF > ./ansible/configs/cp4waiops-roks-custom.yaml
              ---
              # *************************************************************************************************************************************************
              # --------------------------------------------------------------------------------------------------------------------------------------
              # Global Configuration
              # --------------------------------------------------------------------------------------------------------------------------------------
              # *************************************************************************************************************************************************

              global_config:
                environment_name: cp4waiops
                cloud_platform: existing-ocp
                # --------------------------------------------------------------------------------------------------------------------------------------
                # CP4WAIOPS Pull Registires
                # --------------------------------------------------------------------------------------------------------------------------------------
                entitled_registry: cp.icr.io
                entitled_registry_user: cp
                catalog_image: icr.io/cpopen/ibm-operator-catalog:latest
                # Create Welcome Cards in CP4WAIOps
                create_cards: true
                # Create App Menu Items in OCP
                create_ocp_items: true
                # Create Notifications in OCP
                create_ocp_notifications: true
                position_ocp_notifications: BannerTop
                position_final_ocp_notification: BannerTop
                # Use this Password for all Instances
                # Deployment will not work if these aren't changed
                global_password: CHANGEME
                # Set this value to True to accept all licenses
                accept_all_licenses: False
                # Key to decrypt Licenses
                # license_token: NONE


              # *************************************************************************************************************************************************
              # --------------------------------------------------------------------------------------------------------------------------------------
              # OpenShift Configuration
              # --------------------------------------------------------------------------------------------------------------------------------------
              # *************************************************************************************************************************************************
              
              openshift:
              - name: "mycluster"
                ocp_version: "4.12"
                cluster_name: "mycluster"
                domain_name: example.com
                openshift_storage:
                - storage_name: auto-storage
                  storage_type: auto
                  # Alternatively use
                  #storage_name: ibm-roks-storage
                  #storage_type: custom
                  #ocp_storage_class_file: ibmc-file-gold-gid
                  #ocp_storage_class_block: ibmc-block-gold



              # *************************************************************************************************************************************************
              # --------------------------------------------------------------------------------------------------------------------------------------
              # Instance Conficuration
              # --------------------------------------------------------------------------------------------------------------------------------------
              # *************************************************************************************************************************************************
              

              cp4waiops:
              - project: cp4waiops-addons
                instances:
                # --------------------------------------------------------------------------------------------------------------------------------------
                # --------------------------------------------------------------------------------------------------------------------------------------
                # INSTALL TURBONOMIC
                # --------------------------------------------------------------------------------------------------------------------------------------
                # --------------------------------------------------------------------------------------------------------------------------------------
                - name: cp4waiops-turbonomic
                  kind: Turbonomic
                  install: false
                  turbo_version: 8.8.3

                  # --------------------------------------------------------------------------------------------------------------------------------------
                  # Storage Classes Override for this Instance (see comment below)
                  # --------------------------------------------------------------------------------------------------------------------------------------
                  #storage_class_file: automatic
                  #storage_class_block: automatic

                - name: cp4waiops-turbonomic-demo-content
                  kind: TurbonomicDemoContent
                  install: true
                  # Admin User Password (OVERRIDES GLOBAL PASSWORD)
                  #turbo_admin_password: CHANGEME
                  # ---------------------------------------------------------------------
                  # Create Demo User
                  create_user: true
                  # Demo User Name
                  demo_user: demo
                  # Demo User Password (OVERRIDES GLOBAL PASSWORD)
                  #turbo_demo_password: CHANGEME
                  # ---------------------------------------------------------------------
                  # Create Groups
                  group_vcenter_vms: true
                  group_robotshop: true
                  group_licensing: true

                  # ---------------------------------------------------------------------
                  # Create Targets
                  target_instana: true
                  # ---------------------------------------------------------------------
                  # Create Memory and CPU hogs
                  resource_hogs: true
                  # ---------------------------------------------------------------------
                  # Create Metrics server, DIF integration and RobotShop BuisnessApp
                  metrics_dif: true
                  # ---------------------------------------------------------------------
                  # Turbo License (optional)
                  turbo_license: NONE


                    
              EOF





              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 🚀 Prepare Ansible"
              pip install openshift pyyaml kubernetes 
              echo ""
              echo ""



              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 🚀 Starting Installation"
              export ANSIBLE_LOG_PATH=/tmp/ansible.log
              ansible-playbook ./ansible/00_cp4waiops-install.yaml -e "config_file_path=$CONFIG" -e cp_entitlement_key=$ENTITLED_REGISTRY_KEY
              echo ""
              echo ""
              echo "  ⏳ INSTALLATION END TIMESTAMP: $(date)"

              ./tools/98_checkInstallLog.sh

              while true
              do
                sleep 1000
              done


              while true
              do
                sleep 1000
              done


          env:
          - name: INSTALL_REPO
            value : "https://github.com/niklaushirt/cp4waiops-deployer.git"
          - name: CONFIG
            #value : "./configs/cp4waiops-all-34.yaml"
            value : "./configs/cp4waiops-roks-custom.yaml"
            # The pull token for cp.icr.com from https://myibm.ibm.com/products-services/containerlibrary
          - name: ENTITLED_REGISTRY_KEY
            value : "<REGISTRY_TOKEN>"
      restartPolicy: Never
  backoffLimit: 4
