apiVersion: batch/v1
kind: Job
metadata:
  name: waiops-easy-install-all
  namespace: default
spec:
  serviceAccountName: installer-default-default
  template:
    spec:
      containers:
        - name: install
          image: niklaushirt/cp4waiops-tools:2.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "1256Mi"
              cpu: "1200m"
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/bash
              #set -x

              echo "*****************************************************************************************************************************"
              echo " âœ… STARTING: INSTALL AI Manager with Demo Content"
              echo "*****************************************************************************************************************************"
              echo ""
              echo "  â³ INSTALLATION START TIMESTAMP: $(date)"
              echo ""
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " ðŸ“¥ Clone Repo $INSTALL_REPO"
              git clone $INSTALL_REPO
              cd cp4waiops-deployer
              echo ""
              echo ""

              echo "Training@2023" > /tmp/SCRIPT_PWD.txt

              ansible-vault decrypt  --vault-password-file /tmp/LICENSES_PWD.txt ./tools/11_practicum/turbonomic/TURBO_LICENSE.enc --output /tmp/TURBO_LICENSE.sh
              /tmp/TURBO_LICENSE.sh



              echo "*****************************************************************************************************************************"
              echo " âœ… DONE"
              echo "*****************************************************************************************************************************"


              while true
              do
                sleep 1000
              done


          env:
          - name: INSTALL_REPO
            value : "https://github.com/niklaushirt/cp4waiops-deployer.git -b 3.6_dev"
          - name: LICENSE_KEY
            value : "CHANGEME"
      restartPolicy: Never
  backoffLimit: 4
