

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#         ________  __  ___     ___    ________       
#        /  _/ __ )/  |/  /    /   |  /  _/ __ \____  _____
#        / // __  / /|_/ /    / /| |  / // / / / __ \/ ___/
#      _/ // /_/ / /  / /    / ___ |_/ // /_/ / /_/ (__  ) 
#     /___/_____/_/  /_/    /_/  |_/___/\____/ .___/____/  
#                                           /_/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS
#
#  CloudPak for Watson AIOps
#
#  ©2023 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - Turbonomic
#  - Turbonomic Demo Content
#     - Demo User
#     - RobotShop Demo App with synthetic metric
#     - Instana target (if Instana is installed - you have to enter the API Token Manually)
#     - Groups for vCenter and RobotShop
#     - Groups for licensing
#     - Resource Hogs
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 
 
 
- name: ✴️ ✴️ ✴️ INSTALLATION MODULE START - {{current_cp4waiops_feature.kind}}
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "      🟡🟡🟡🟡🟡  🚀 CloudPak for Watson AIOps - INSTALLING {{current_cp4waiops_feature.kind}} 🟡🟡🟡🟡🟡                                                        "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"


- name: 📣 OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    export WAIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
    appURL=$(oc get routes -n $WAIOPS_NAMESPACE-demo-ui $WAIOPS_NAMESPACE-demo-ui  -o jsonpath="{['spec']['host']}")|| true

    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: cp4waiops-notification-main
    spec:
      backgroundColor: '#141a6b'
      color: '#fff'
      location: {{global_config.position_final_ocp_notification | default("BannerBottom")}}
      text: 'Installing  {{current_cp4waiops_feature.kind}} - Version {{ current_cp4waiops_feature.turbo_version }} - '  
      link:
          href: "https://$OPENSHIFT_ROUTE/k8s/ns/cp4waiops-installer/pods/$INSTALL_POD/logs"
          text: Open Logs    
    EOF
  ignore_errors: true



- name: 🟣 Installing {{current_cp4waiops_feature.kind}} with the following configuration
  debug:
    var: current_cp4waiops_feature


- name:  🟣 Storage Class Parameters - SPECIFIC INSTANCE"
  debug:
    msg:
    - "** Installation Options for SPECIFIC INSTANCE ***********************************************************************"
    - " Storage Class File Override:      {{ current_cp4waiops_feature.storage_class_file}}"
    - " Storage Class Block Override:     {{ current_cp4waiops_feature.storage_class_block}}"
    - " Storage Class InfraManagement:    {{ current_cp4waiops_feature.storage_class_file}}"
    - ""
  when: current_cp4waiops_feature.storage_class_file is defined


- name:  🟣 Storage Class Parameters - GLOBAL"
  debug:
    msg:
    - "** Installation Options from GLOBAL ***********************************************************************"
    - " Storage Class File Override:      {{ ocp_storage_class_file }}"
    - " Storage Class Block Override:     {{ ocp_storage_class_block }}"
    - " Storage Class InfraManagement:    {{ ocp_storage_class_file }}"
    - ""
  when: current_cp4waiops_feature.storage_class_file is not defined and ocp_storage_class_file is defined


# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Placeholder for customization
- name: 🟡🟡🟡 Initialize Custom Hook
  include_tasks: 00_init-custom-hook.yaml

# Initialize Logging
- name: 🟡🟡🟡 Initialize Logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/01_init-logging.yaml"

- name: 🟡🟡🟡 Get Storage Class
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/05_init-get-storage-class.yaml"

  
# Start block
- name: 🟡🟡🟡 Start Logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/90-log-start.yaml"




# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL TURBONOMIC
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Install TURBONOMIC
- name: 🟡🟡🟡 Install Turbonomic
  include_tasks: 10_addons-turbonomic.yaml


- name: 🟡🟡🟡 Restart Demo UI
  include_tasks: 21_addons-turbonomic-restart-demoui.yaml

- name: 🟡🟡🟡 Install OCP Menu Item
  include_tasks: 91_addons-turbonomic-create-ocp-tools-menu.yaml
  when: global_config.create_ocp_items | default(true) == true  

# Update CP4WAIOps Cards
- name: 🟡🟡🟡 Update CP4WAIOps Cards
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/99_update_cards.yaml"




- name: 🟡🟡🟡 End Logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/91-log-end.yaml"


- name: ✅ INSTALLATION MODULE DONE - {{current_cp4waiops_feature.kind}}
  debug: 
    msg:  

    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       ✅ CloudPak for Watson AIOps - DONE INSTALLING {{current_cp4waiops_feature.kind}}                                                                                 "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
