apiVersion: v1
kind: ServiceAccount
metadata:
  name: waiops-event-gateway-admin
  namespace: cp4waiops
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: waiops-event-gateway-admin-crb
subjects:
  - kind: ServiceAccount
    name: waiops-event-gateway-admin
    namespace: cp4waiops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---

apiVersion: v1
kind: ConfigMap
metadata:
  name:  waiops-event-gateway-config
  namespace: cp4waiops
data:
  TOKEN: 'P4ssw0rd!'
  ITERATE_ELEMENT: 'events'
  WEBHOOK_DEBUG: 'true'
  EVENT_TEMPLATE: '{"id": "1a2a6787-59ad-4acd-bd0d-46c1ddfd8e00","occurrenceTime": "@@TIMESTAMP_DATE","summary": "@@SUMMARY_TEXT","severity": @@SEVERITY_NUMBER,"type": {"eventType": "problem","classification": "@@MANAGER_NAME"},"expirySeconds": @@EXPIRY_SECONDS,"links": [{"linkType": "webpage","name": "@@MANAGER_NAME","description": "@@MANAGER_NAME","url": "@@URL_TXT"}],"sender": {"type": "host","name": "@@SENDER_NAME","sourceId": "@@SENDER_NAME"},"resource": {"type": "host","name": "@@RESOURCE_NAME","sourceId": "@@RESOURCE_NAME"},"details": {@@DETAILS_JSON}}' 
  EVENT_MAPPING: |- 
      kubernetes.container_name,RESOURCE_NAME;
      kubernetes.namespace_name,SENDER_NAME;
      @rawstring,SUMMARY_TEXT;
      override_with_date,TIMESTAMP_DATE;
      URL,URL_TXT;
      Severity,SEVERITY_NUMBER;
      Expiry,EXPIRY_SECONDS;
      details,DETAILS_JSON;
      Manager,MANAGER_NAME



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waiops-event-gateway
  namespace: cp4waiops
  labels:
      app:  waiops-event-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  waiops-event-gateway
  template:
    metadata:
      labels:
        app:  waiops-event-gateway
    spec:
      containers:
      - image: niklaushirt/cp4waiops-webhook-python:0.4
        imagePullPolicy: Always
        name: gateway
        command:
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "550m"
            memory: "550Mi"
        envFrom:
        - configMapRef:
            name:  waiops-event-gateway-config
      serviceAccountName: waiops-event-gateway-admin         
---
apiVersion: v1
kind: Service
metadata:
  name:  waiops-event-gateway-service
  namespace: cp4waiops
spec:
  selector:
    app:  waiops-event-gateway
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name:  cp4waiops-event-gateway
  namespace: cp4waiops
spec:
  to:
    kind: Service
    name:  waiops-event-gateway-service

