apiVersion: v1
kind: ServiceAccount
metadata:
  name: waiops-falco-gateway-admin
  namespace: cp4waiops
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: waiops-falco-gateway-admin-crb
subjects:
  - kind: ServiceAccount
    name: waiops-falco-gateway-admin
    namespace: cp4waiops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---

apiVersion: v1
kind: ConfigMap
metadata:
  name:  waiops-falco-gateway-config
  namespace: cp4waiops
data:
  TOKEN: '46c1ddfd8e00'
  ITERATE_ELEMENT: 'events'
  WEBHOOK_DEBUG: 'true'
  EVENT_TEMPLATE: '{"id": "1a2a6787-59ad-4acd-bd0d-46c1ddfd8e00","occurrenceTime":"@@TIMESTAMP_DATE","summary": "@@SUMMARY_TEXT","severity": 3,"type":{"eventType": "problem","classification": "Falco - @@MANAGER_NAME"},"expirySeconds":@@EXPIRY_SECONDS,"links": [{"linkType": "webpage","name":"Falco - @@MANAGER_NAME","description": "Falco - @@MANAGER_NAME","url":"@@URL_TXT"}],"sender": {"type": "host","name": "Falco","sourceId":"@@SENDER_NAME"},"resource": {"type": "host","name":"@@RESOURCE_NAME","sourceId": "@@RESOURCE_NAME"},"details": {"output": "@@DETAILS_JSON"}}' 
  EVENT_MAPPING: |- 
    output_fields.container@name,RESOURCE_NAME;
    output_fields.k8s@ns@name,SENDER_NAME;
    rule,SUMMARY_TEXT;
    override_with_date,TIMESTAMP_DATE;
    URL,URL_TXT;
    NONE,SEVERITY_NUMBER;
    60000,EXPIRY_SECONDS;
    output,DETAILS_JSON;
    priority,MANAGER_NAME



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waiops-falco-gateway
  namespace: cp4waiops
  labels:
      app:  waiops-falco-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  waiops-falco-gateway
  template:
    metadata:
      labels:
        app:  waiops-falco-gateway
    spec:
      containers:
      - image: niklaushirt/cp4waiops-webhook-python:0.5
        imagePullPolicy: Always
        name: gateway
        command:
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "550m"
            memory: "550Mi"
        envFrom:
        - configMapRef:
            name:  waiops-falco-gateway-config
      serviceAccountName: waiops-falco-gateway-admin         
---
apiVersion: v1
kind: Service
metadata:
  name:  waiops-falco-gateway-service
  namespace: cp4waiops
spec:
  selector:
    app:  waiops-falco-gateway
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name:  cp4waiops-falco-gateway
  namespace: cp4waiops
spec:
  to:
    kind: Service
    name:  waiops-falco-gateway-service

